apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-router
  labels:
    name: edge-router
spec:
  selector:
    matchLabels:
      name: edge-router
  replicas: 1
  template:
    metadata:
      labels:
        name: edge-router
    spec:
      containers:
      - name: edge-router
        image: amjaad/edge
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 99m
            memory: 100Mi
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
      nodeSelector:
        beta.kubernetes.io/os: linux
