apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: orders-src
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/amjaadabdullah/level3-project
