apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: orders-runner
spec:
  serviceAccountName: amjaad-docker
  taskRef:
    name: orders
  params:
  - name: IMAGE
    value: "amjaad/orders"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: orders-res
