
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: payment-runner
  namespace: test
spec:
  serviceAccountName: amjaad-docker
  taskRef:
    name: payment
  params:
  - name: IMAGE
    value: "amjaad/payment"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: payment-re

