apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: qm-runner
  namespace: test
spec:
  serviceAccountName: amjaad-docker
  taskRef:
    name: queue-master
  params:
  - name: IMAGE
    value: "amjaad/queuemaster"
  resources:
    inputs:
    - name: queue-m
      resourceRef:
        name: queue-m
